name: Build
on:
  pull_request:
  push:
    branches-ignore:
      - main
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run: sudo npm install -g yarn && yarn install
      - name: Run build
        run: yarn build || exit 1
