name: Build
on: pull_request
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run build
        run: |
          sudo npm install -g yarn
          cd Frontend
          yarn install
          yarn build || exit 1
