name: Deploy
on:
  push:
    branches: [main]

env:
  REGION: us-west-2
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Sets up AWS profile.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      # Install CDK
      - name: Install CDK
        run: sudo npm install -g aws-cdk@1.95.1
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      # Build and deploy the backend 
      - name: Build backend
        run: |
          cd $GITHUB_WORKSPACE
          chmod 700 deployBackend.sh
          ./deployBackend.sh -c -e test
      # Install frontend packages
      - name: Install packages
        run: |
          sudo npm install -g yarn
          cd Frontend
          yarn install
      # Run E2E tests
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./Frontend
          browser: chrome
          headless: true
          start: yarn start || exit 1
          wait-on: 'http://localhost:3000'
  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Sets up AWS profile.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      # Install CDK
      - name: Install CDK
        run: sudo npm install -g aws-cdk@1.95.1
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      # Build and deploy to production
      - name: Build and deploy
        run: |
          cd $GITHUB_WORKSPACE
          chmod 700 deploy.sh
          ./deploy.sh -e prod